version: '3.8'

services:
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    ports:
      - "3000:3000"
    restart: unless-stopped

  pdf-sdk:
    build: .
    container_name: pdf-sdk
    ports:
      - "8080:8080"
    environment:
      - GOTENBERG_URL=http://gotenberg:3000
      - SERVICE_NAME=convert-pdf-go-sdk
      - LOGGER_LEVEL=info
    depends_on:
      - gotenberg
    restart: unless-stopped
